-- 修脚师考试刷题系统 - Supabase 建表SQL (安全加固版)
-- 请在 Supabase SQL Editor 中依次执行以下语句

-- 0. 启用 UUID 扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. students 表 - 学生账号
CREATE TABLE IF NOT EXISTS students (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL DEFAULT '123456',
  nickname VARCHAR NOT NULL,
  cohort VARCHAR NOT NULL,
  level VARCHAR DEFAULT '初级',
  status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'expired')),
  expires_at TIMESTAMPTZ DEFAULT (now() + interval '1 year'),
  can_change_level BOOLEAN DEFAULT false,
  xp INTEGER DEFAULT 0,
  study_level INTEGER DEFAULT 1,
  session_id VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. questions 表 - 题库
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR NOT NULL CHECK (type IN ('single', 'multiple', 'judge')),
  content TEXT NOT NULL,
  options JSONB,
  answer VARCHAR NOT NULL,
  analysis TEXT,
  tags TEXT[],
  cohort VARCHAR,
  level VARCHAR DEFAULT '初级',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. records 表 - 答题记录
CREATE TABLE IF NOT EXISTS records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id VARCHAR NOT NULL,
  question_id BIGINT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  user_answer VARCHAR,
  is_fav BOOLEAN DEFAULT false,
  exam_id BIGINT,
  guest_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. exams 表 - 考试
CREATE TABLE IF NOT EXISTS exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  cohort VARCHAR NOT NULL,
  question_ids BIGINT[] NOT NULL,
  duration INT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  level VARCHAR DEFAULT '初级',
  is_quick BOOLEAN DEFAULT false,
  pass_rate INT DEFAULT 60,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_students_username ON students(username);
CREATE INDEX IF NOT EXISTS idx_students_cohort ON students(cohort);
CREATE INDEX IF NOT EXISTS idx_students_level ON students(level);
CREATE INDEX IF NOT EXISTS idx_questions_type ON questions(type);
CREATE INDEX IF NOT EXISTS idx_questions_cohort ON questions(cohort);
CREATE INDEX IF NOT EXISTS idx_questions_level ON questions(level);
CREATE INDEX IF NOT EXISTS idx_records_student_id ON records(student_id);
CREATE INDEX IF NOT EXISTS idx_records_question_id ON records(question_id);
CREATE INDEX IF NOT EXISTS idx_records_exam_id ON records(exam_id);
CREATE INDEX IF NOT EXISTS idx_exams_cohort ON exams(cohort);
CREATE INDEX IF NOT EXISTS idx_exams_level ON exams(level);
CREATE INDEX IF NOT EXISTS idx_records_created_at ON records(created_at);
CREATE INDEX IF NOT EXISTS idx_records_student_question ON records(student_id, question_id);
CREATE INDEX IF NOT EXISTS idx_records_student_exam ON records(student_id, exam_id);
CREATE INDEX IF NOT EXISTS idx_exams_is_quick ON exams(is_quick);
CREATE INDEX IF NOT EXISTS idx_exams_start_time ON exams(start_time);
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

-- RLS 安全策略
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;

-- 删除旧策略（如果存在）
DROP POLICY IF EXISTS "Allow all on students" ON students;
DROP POLICY IF EXISTS "Allow all on questions" ON questions;
DROP POLICY IF EXISTS "Allow all on records" ON records;
DROP POLICY IF EXISTS "Allow all on exams" ON exams;
DROP POLICY IF EXISTS "允许读取学生表" ON students;
DROP POLICY IF EXISTS "允许插入学生" ON students;
DROP POLICY IF EXISTS "允许更新学生" ON students;
DROP POLICY IF EXISTS "允许删除学生" ON students;
DROP POLICY IF EXISTS "允许读取题库" ON questions;
DROP POLICY IF EXISTS "允许管理题库" ON questions;
DROP POLICY IF EXISTS "允许读取记录" ON records;
DROP POLICY IF EXISTS "允许插入记录" ON records;
DROP POLICY IF EXISTS "允许更新记录" ON records;
DROP POLICY IF EXISTS "允许读取考试" ON exams;
DROP POLICY IF EXISTS "允许管理考试" ON exams;

-- students表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取学生表" ON students FOR SELECT USING (true);
CREATE POLICY "允许插入学生" ON students FOR INSERT WITH CHECK (true);
CREATE POLICY "允许更新学生" ON students FOR UPDATE USING (true);
CREATE POLICY "允许删除学生" ON students FOR DELETE USING (true);

-- questions表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取题库" ON questions FOR SELECT USING (true);
CREATE POLICY "允许管理题库" ON questions FOR ALL USING (true) WITH CHECK (true);

-- records表 - 读取和插入开放，更新允许（收藏等）
CREATE POLICY "允许读取记录" ON records FOR SELECT USING (true);
CREATE POLICY "允许插入记录" ON records FOR INSERT WITH CHECK (true);
CREATE POLICY "允许更新记录" ON records FOR UPDATE USING (true);

-- exams表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取考试" ON exams FOR SELECT USING (true);
CREATE POLICY "允许管理考试" ON exams FOR ALL USING (true) WITH CHECK (true);

-- 5. admins 表 - 管理员账号
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL DEFAULT '123456',
  nickname VARCHAR NOT NULL,
  is_master BOOLEAN DEFAULT false,
  session_id VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 插入主管理员（仅首次）
INSERT INTO admins (username, password, nickname, is_master)
VALUES ('admin', 'admin888', '主管理员', true)
ON CONFLICT (username) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

-- admins表 RLS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理管理员" ON admins;
CREATE POLICY "允许管理管理员" ON admins FOR ALL USING (true) WITH CHECK (true);

-- 6. enroll_configs 表 - 报名配置
CREATE TABLE IF NOT EXISTS enroll_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  levels TEXT[] NOT NULL,
  cohort VARCHAR,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  auto_sync BOOLEAN DEFAULT false,
  status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. enrollments 表 - 报名记录
CREATE TABLE IF NOT EXISTS enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id BIGINT NOT NULL REFERENCES enroll_configs(id) ON DELETE CASCADE,
  name VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  level VARCHAR NOT NULL,
  status VARCHAR DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 报名表索引
CREATE INDEX IF NOT EXISTS idx_enroll_configs_status ON enroll_configs(status);
CREATE INDEX IF NOT EXISTS idx_enroll_configs_created_at ON enroll_configs(created_at);
CREATE INDEX IF NOT EXISTS idx_enrollments_config_id ON enrollments(config_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_phone ON enrollments(phone);
CREATE INDEX IF NOT EXISTS idx_enrollments_status ON enrollments(status);

-- enroll_configs 表 RLS
ALTER TABLE enroll_configs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理报名配置" ON enroll_configs;
CREATE POLICY "允许管理报名配置" ON enroll_configs FOR ALL USING (true) WITH CHECK (true);

-- enrollments 表 RLS
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理报名记录" ON enrollments;
CREATE POLICY "允许管理报名记录" ON enrollments FOR ALL USING (true) WITH CHECK (true);

-- 8. homeworks 表 - 作业配置
CREATE TABLE IF NOT EXISTS homeworks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  cohort VARCHAR,
  level VARCHAR DEFAULT '初级',
  target_ids BIGINT[] NOT NULL,
  question_ids BIGINT[] NOT NULL,
  duration INT NOT NULL DEFAULT 60,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  created_by UUID,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 9. homework_records 表 - 作业答题记录
CREATE TABLE IF NOT EXISTS homework_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id BIGINT NOT NULL REFERENCES homeworks(id) ON DELETE CASCADE,
  student_id VARCHAR NOT NULL,
  question_id BIGINT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  user_answer VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 作业表索引
CREATE INDEX IF NOT EXISTS idx_homeworks_status ON homeworks(status);
CREATE INDEX IF NOT EXISTS idx_homeworks_cohort ON homeworks(cohort);
CREATE INDEX IF NOT EXISTS idx_homeworks_level ON homeworks(level);
CREATE INDEX IF NOT EXISTS idx_homework_records_homework_id ON homework_records(homework_id);
CREATE INDEX IF NOT EXISTS idx_homework_records_student_id ON homework_records(student_id);

-- homeworks 表 RLS
ALTER TABLE homeworks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理作业" ON homeworks;
CREATE POLICY "允许管理作业" ON homeworks FOR ALL USING (true) WITH CHECK (true);

-- homework_records 表 RLS
ALTER TABLE homework_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理作业记录" ON homework_records;
CREATE POLICY "允许管理作业记录" ON homework_records FOR ALL USING (true) WITH CHECK (true);

-- 10. operation_logs 表 - 操作日志
CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID,
  action VARCHAR NOT NULL,
  target_type VARCHAR,
  target_id VARCHAR,
  details JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 操作日志索引
CREATE INDEX IF NOT EXISTS idx_operation_logs_admin_id ON operation_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_operation_logs_created_at ON operation_logs(created_at);

-- operation_logs 表 RLS
ALTER TABLE operation_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理操作日志" ON operation_logs;
CREATE POLICY "允许管理操作日志" ON operation_logs FOR ALL USING (true) WITH CHECK (true);
