-- 修脚师考试刷题系统 - Supabase 建表SQL (安全加固版)
-- 请在 Supabase SQL Editor 中依次执行以下语句

-- 0. 启用 UUID 扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. students 表 - 学生账号
CREATE TABLE IF NOT EXISTS students (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL DEFAULT '123456',
  nickname VARCHAR NOT NULL,
  cohort VARCHAR NOT NULL,
  level VARCHAR DEFAULT '初级',
  status VARCHAR DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'expired')),
  expires_at TIMESTAMPTZ DEFAULT (now() + interval '1 year'),
  can_change_level BOOLEAN DEFAULT false,
  xp INTEGER DEFAULT 0,
  study_level INTEGER DEFAULT 1,
  session_id VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. questions 表 - 题库
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR NOT NULL CHECK (type IN ('single', 'multiple', 'judge')),
  content TEXT NOT NULL,
  options JSONB,
  answer VARCHAR NOT NULL,
  analysis TEXT,
  tags TEXT[],
  cohort VARCHAR,
  level VARCHAR DEFAULT '初级',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. records 表 - 答题记录
CREATE TABLE IF NOT EXISTS records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id VARCHAR NOT NULL,
  question_id BIGINT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  user_answer VARCHAR,
  is_fav BOOLEAN DEFAULT false,
  exam_id BIGINT,
  guest_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. exams 表 - 考试
CREATE TABLE IF NOT EXISTS exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  cohort VARCHAR NOT NULL,
  question_ids BIGINT[] NOT NULL,
  duration INT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  level VARCHAR DEFAULT '初级',
  is_quick BOOLEAN DEFAULT false,
  pass_rate INT DEFAULT 60,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 索引优化
CREATE INDEX IF NOT EXISTS idx_students_username ON students(username);
CREATE INDEX IF NOT EXISTS idx_students_cohort ON students(cohort);
CREATE INDEX IF NOT EXISTS idx_students_level ON students(level);
CREATE INDEX IF NOT EXISTS idx_questions_type ON questions(type);
CREATE INDEX IF NOT EXISTS idx_questions_cohort ON questions(cohort);
CREATE INDEX IF NOT EXISTS idx_questions_level ON questions(level);
CREATE INDEX IF NOT EXISTS idx_records_student_id ON records(student_id);
CREATE INDEX IF NOT EXISTS idx_records_question_id ON records(question_id);
CREATE INDEX IF NOT EXISTS idx_records_exam_id ON records(exam_id);
CREATE INDEX IF NOT EXISTS idx_exams_cohort ON exams(cohort);
CREATE INDEX IF NOT EXISTS idx_exams_level ON exams(level);
CREATE INDEX IF NOT EXISTS idx_records_created_at ON records(created_at);
CREATE INDEX IF NOT EXISTS idx_records_student_question ON records(student_id, question_id);
CREATE INDEX IF NOT EXISTS idx_records_student_exam ON records(student_id, exam_id);
CREATE INDEX IF NOT EXISTS idx_exams_is_quick ON exams(is_quick);
CREATE INDEX IF NOT EXISTS idx_exams_start_time ON exams(start_time);
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

-- RLS 安全策略
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE records ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;

-- 删除旧策略（如果存在）
DROP POLICY IF EXISTS "Allow all on students" ON students;
DROP POLICY IF EXISTS "Allow all on questions" ON questions;
DROP POLICY IF EXISTS "Allow all on records" ON records;
DROP POLICY IF EXISTS "Allow all on exams" ON exams;
DROP POLICY IF EXISTS "允许读取学生表" ON students;
DROP POLICY IF EXISTS "允许插入学生" ON students;
DROP POLICY IF EXISTS "允许更新学生" ON students;
DROP POLICY IF EXISTS "允许删除学生" ON students;
DROP POLICY IF EXISTS "允许读取题库" ON questions;
DROP POLICY IF EXISTS "允许管理题库" ON questions;
DROP POLICY IF EXISTS "允许读取记录" ON records;
DROP POLICY IF EXISTS "允许插入记录" ON records;
DROP POLICY IF EXISTS "允许更新记录" ON records;
DROP POLICY IF EXISTS "允许读取考试" ON exams;
DROP POLICY IF EXISTS "允许管理考试" ON exams;

-- students表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取学生表" ON students FOR SELECT USING (true);
CREATE POLICY "允许插入学生" ON students FOR INSERT WITH CHECK (true);
CREATE POLICY "允许更新学生" ON students FOR UPDATE USING (true);
CREATE POLICY "允许删除学生" ON students FOR DELETE USING (true);

-- questions表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取题库" ON questions FOR SELECT USING (true);
CREATE POLICY "允许管理题库" ON questions FOR ALL USING (true) WITH CHECK (true);

-- records表 - 读取和插入开放，更新允许（收藏等）
CREATE POLICY "允许读取记录" ON records FOR SELECT USING (true);
CREATE POLICY "允许插入记录" ON records FOR INSERT WITH CHECK (true);
CREATE POLICY "允许更新记录" ON records FOR UPDATE USING (true);

-- exams表 - 读取开放，写操作前端控制管理员权限
CREATE POLICY "允许读取考试" ON exams FOR SELECT USING (true);
CREATE POLICY "允许管理考试" ON exams FOR ALL USING (true) WITH CHECK (true);

-- 5. admins 表 - 管理员账号
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL DEFAULT '123456',
  nickname VARCHAR NOT NULL,
  is_master BOOLEAN DEFAULT false,
  session_id VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 插入主管理员（仅首次）
INSERT INTO admins (username, password, nickname, is_master)
VALUES ('admin', 'admin888', '主管理员', true)
ON CONFLICT (username) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username);

-- admins表 RLS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "允许管理管理员" ON admins;
CREATE POLICY "允许管理管理员" ON admins FOR ALL USING (true) WITH CHECK (true);
